'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.mentors': 'Mentors',
    'nav.sessions': 'Sessions',
    'nav.chat': 'Chat',
    'nav.reports': 'Rapports',
    'nav.calendar': 'Calendrier',
    'tools.matching': 'Matching IA',
    'tools.profile': 'Mon profil',
    'tools.disponibilites': 'Mes disponibilités',

    // Home page
    'home.badge': 'Plateforme de mentorat nouvelle génération',
    'home.hero_title': 'Trouvez le mentor qui',
    'home.hero_subtitle': 'vous révélera',
    'home.hero_description': 'Rejoignez notre communauté et accélérez votre apprentissage grâce à un mentorat personnalisé avec matching IA',
    'home.start_free': 'Commencer gratuitement',
    'home.view_mentors': 'Voir les mentors',
    'home.stats_mentors': 'Mentors experts',
    'home.stats_sessions': 'Sessions réalisées',
    'home.stats_satisfaction': 'Taux de satisfaction',
    'home.stats_support': 'Support disponible',
    'home.why_choose_us': 'Pourquoi choisir notre plateforme ?',
    'home.why_choose_us_desc': 'Une expérience de mentorat complète et innovante',
    'home.feature_matching': 'Matching IA',
    'home.feature_matching_desc': 'Trouvez le mentor parfait grâce à notre algorithme intelligent',
    'home.feature_booking': 'Réservation facile',
    'home.feature_booking_desc': 'Planifiez vos sessions en quelques clics',
    'home.feature_chat': 'Chat en temps réel',
    'home.feature_chat_desc': 'Communications instantanées avec votre mentor',
    'home.feature_video': 'Visioconférence',
    'home.feature_video_desc': 'Sessions en ligne avec lien intégré',
    'home.feature_certification': 'Certification',
    'home.feature_certification_desc': 'Obtenez des certificats de progression',
    'home.feature_security': 'Sécurisé',
    'home.feature_security_desc': 'Plateforme sécurisée et confidentielle',
    'home.cta_title': 'Prêt à commencer votre parcours ?',
    'home.cta_description': "Rejoignez des milliers d'étudiants qui ont déjà trouvé leur mentor idéal",
    'home.cta_button': 'Inscription gratuite',
    'home.find_mentor': 'Trouver un mentor',
    'home.explore_by_domain': 'Explorer par domaine',
    'home.explore_by_domain_desc': "Trouvez un mentor dans votre domaine d'intérêt",
    'home.view_all_domains': 'Voir tous les domaines',
    'footer.title': 'Plateforme de Mentorat Académique',
    'footer.project': "Projet de Fin d'Études",

    // Dashboard
    'dashboard.welcome': 'Bienvenue',
    'dashboard.activity': 'Votre activité',
    'dashboard.quick_access': 'Accès rapide',
    'dashboard.sessions': 'Mes sessions',
    'dashboard.messages': 'Messagerie',
    'dashboard.reports': 'Rapports',
    'dashboard.find_mentor': 'Trouver un mentor',
    'dashboard.recommendations': 'Recommandations IA',
    'dashboard.sessions_desc': 'Voir et gérer vos sessions',
    'dashboard.messages_desc': 'Discuter avec vos contacts',
    'dashboard.reports_desc': 'Télécharger vos rapports',
    'dashboard.find_mentor_desc': 'Rechercher des mentors',
    'dashboard.recommendations_desc': 'Mentors suggérés pour vous',
    'dashboard.recent_sessions': 'Sessions récentes',
    'dashboard.unread': 'Non lus',

    // Profile
    'profile.title': 'Mon profil',
    'profile.edit': 'Modifier',
    'profile.save': 'Enregistrer',
    'profile.photo': 'Photo de profil',
    'profile.info': 'Informations personnelles',
    'profile.experience': 'Expérience',
    'profile.progression': 'Progression',
    'profile.note': 'Note moyenne',
    'profile.disponibilites': 'Mes disponibilités',
    'profile.disponibilites_desc': 'Gérer vos créneaux',
    'profile.nom_complet': 'Nom complet',
    'profile.domaine': 'Domaine',
    'profile.domaine_placeholder': 'Ex: Informatique, Marketing, Design...',
    'profile.bio': 'Biographie',
    'profile.bio_placeholder': 'Présentez votre parcours et votre expertise...',
    'profile.annees_experience': "Années d'expérience",
    'profile.disponible': 'Disponible pour mentorat',
    'profile.indisponible': 'Indisponible',
    'profile.cv': 'CV (PDF)',
    'profile.view_cv': 'Voir le CV actuel',
    'profile.replace_cv': 'Remplacer le CV',
    'profile.upload_cv': 'Uploader le CV',
    'profile.niveau_etude': "Niveau d'étude",
    'profile.niveau_etude_placeholder': 'Ex: Licence 3, Master 2, Doctorat...',
    'profile.objectifs': "Objectifs d'apprentissage",
    'profile.objectifs_placeholder': "Décrivez vos objectifs d'apprentissage...",
    'profile.tags': 'Mots-clés pour le matching IA',
    'profile.tags_desc': "Ces mots-clés sont utilisés par l'algorithme IA pour trouver les meilleurs mentors.",
    'profile.tags_placeholder': 'Ex: python, machine learning...',
    'profile.tags_hint': 'Appuyez sur Entrée ou , pour ajouter un tag',
    'common.saving': 'Enregistrement...',

    // ── AUTH ──────────────────────────────────────────────────────────────────
    'auth.login_hero_title': 'Bon retour parmi nous',
    'auth.login_hero_desc': 'Connectez-vous pour retrouver vos sessions, vos mentors et votre progression.',
    'auth.login_title': 'Connexion',
    'auth.login_subtitle': 'Accédez à votre espace personnel',
    'auth.login_button': 'Se connecter',
    'auth.login_error': 'Email ou mot de passe incorrect',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.register_link': "S'inscrire",
    'auth.forgot_password': 'Mot de passe oublié ?',

    'auth.register_hero_title': 'Rejoignez la communauté',
    'auth.register_hero_desc': "Créez votre compte et commencez votre parcours de mentorat dès aujourd'hui.",
    'auth.register_title': 'Inscription',
    'auth.register_subtitle': 'Créez votre compte gratuitement',
    'auth.register_button': "S'inscrire",
    'auth.register_success': 'Inscription réussie ! Bienvenue 🎉',
    'auth.register_error': "Erreur lors de l'inscription",
    'auth.have_account': 'Déjà un compte ?',
    'auth.login_link': 'Se connecter',

    'auth.email': 'Adresse email',
    'auth.password': 'Mot de passe',
    'auth.lastname': 'Nom',
    'auth.firstname': 'Prénom',
    'auth.or': 'ou',

    'auth.fields_required': 'Veuillez remplir tous les champs',
    'auth.password_requirements': 'Le mot de passe ne respecte pas les critères requis',
    'auth.password_min_length': '8 caractères minimum',
    'auth.password_uppercase': 'Une majuscule',
    'auth.password_number': 'Un chiffre',

    'auth.i_am': 'Je suis',
    'auth.role_mentee': 'Mentoré(e)',
    'auth.role_mentee_desc': "J'apprends",
    'auth.role_mentor': 'Mentor',
    'auth.role_mentor_desc': "J'accompagne",

    'auth.google_error': 'Erreur de connexion avec Google',
    'auth.google_cancelled': 'Connexion Google annulée',

    'auth.feat1_title': 'Matching IA intelligent',
    'auth.feat1_desc': 'Trouvez le mentor parfait grâce à notre algorithme.',
    'auth.feat2_title': 'Objectifs personnalisés',
    'auth.feat2_desc': 'Suivez votre progression à chaque session.',
    'auth.feat3_title': 'Plateforme sécurisée',
    'auth.feat3_desc': 'Vos données et échanges sont protégés.',
    'auth.feat4_title': 'Rapports détaillés',
    'auth.feat4_desc': 'Téléchargez vos comptes-rendus de session en PDF.',

    // Sessions
    'sessions.title': 'Mes sessions',
    'sessions.all': 'Toutes',
    'sessions.pending': 'En attente',
    'sessions.confirmed': 'Confirmées',
    'sessions.in_progress': 'En cours',
    'sessions.completed': 'Terminées',
    'sessions.cancelled': 'Annulées',
    'sessions.confirm': 'Confirmer',
    'sessions.cancel': 'Annuler',
    'sessions.start': 'Démarrer',
    'sessions.chat': 'Chat',
    'sessions.with': 'Avec',
    'sessions.started': 'Session démarrée',
    'sessions.cancel_confirm': 'Annuler cette session ?',
    'sessions.no_sessions': 'Aucune session trouvée',
    'sessions.subtitle': 'Espace mentorat',
    'sessions.page_description': 'Consultez, validez et planifiez vos échanges de mentorat.',
    'sessions.upcoming': 'À venir',
    'sessions.history': 'Historique',
    'sessions.total': 'Total',
    'sessions.new_session': 'Nouvelle session',
    'sessions.empty_title': 'Aucune session',
    'sessions.empty_mentee': 'Réservez votre premier mentor pour commencer.',
    'sessions.empty_mentor': "Attendez qu'un mentoré vous contacte.",
    'sessions.explore_mentors': 'Explorer les mentors',
    'sessions.label_mentee': 'Mentoré',
    'sessions.label_mentor': 'Mentor',
    'sessions.reviewed': 'Noté',
    'sessions.visio': 'Visio',
    'sessions.rate': 'Noter',
    'sessions.view_report': 'Consulter Rapport',

    // Chat
    'chat.title': 'Messagerie',
    'chat.subtitle': 'Discutez avec vos mentors et mentorés',
    'chat.no_conversation': 'Aucune conversation',
    'chat.no_conversation_desc': "Vous n'avez pas encore de sessions actives.",
    'chat.start': 'Commencez la conversation !',
    'chat.search_placeholder': 'Rechercher...',
    'chat.no_conversations_desc_alt': 'Réservez une session pour commencer à discuter',
    'chat.yesterday': 'Hier',
    'chat.today': "Aujourd'hui",
    'chat.online': 'En ligne',
    'chat.typing': 'écrit...',

    // Reports
    'reports.title': 'Rapports',
    'reports.subtitle': 'Générez et téléchargez vos rapports',
    'reports.no_sessions': 'Aucune session terminée',
    'reports.no_sessions_desc': 'Les rapports seront disponibles une fois vos sessions terminées.',
    'reports.generate': 'Générer',
    'reports.download': 'Télécharger',
    'reports.generating': 'Génération du rapport...',
    'reports.downloaded': 'Rapport téléchargé !',
    'reports.search_placeholder': 'Rechercher un rapport par sujet ou nom...',
    'reports.no_search_results': 'Aucun résultat',
    'reports.no_search_results_desc': 'Aucun rapport ne correspond à votre recherche.',
    'reports.by_author': 'Par le {role} {name}',
    'reports.no_summary': 'Téléchargez le rapport PDF pour consulter le compte-rendu complet de cette session.',
    'reports.view_full': 'Consulter en entier',
    'reports.session_reports': 'Rapports de la session',
    'reports.session_report': 'Rapport de session',
    'reports.report': 'Rapport',
    'reports.no_reports': 'Aucun rapport généré',
    'reports.no_reports_yet': 'Aucun rapport',
    'reports.no_reports_desc': 'Générez un rapport pour cette session',
    'reports.generate_report': 'Générer le rapport',
    'reports.existing_reports': 'Rapports existants',
    'reports.regenerate': 'Régénérer',
    'reports.view_details': 'Voir les détails',
    'reports.downloading': 'Téléchargement du rapport...',
    'reports.generated': 'Rapport généré avec succès !',
    'reports.back_to_reports': 'Retour aux rapports',
    'reports.generate_quick': 'Générer rapidement',
    'common.back_to_reports': 'Retour aux rapports',

    // Matching
    'matching.title': 'Recommandations IA',
    'matching.subtitle': 'Mentors sélectionnés pour vous',
    'matching.no_results': 'Aucune recommandation',
    'matching.no_results_desc': 'Complétez votre profil et vos objectifs pour recevoir des recommandations personnalisées.',
    'matching.view_profile': 'Voir le profil',
    'matching.book': 'Réserver',
    'matching.mentor_only': 'Le matching IA est réservé aux mentorés',
    'matching.updated': 'Recommandations mises à jour',
    'matching.excellent': 'Excellent match !',
    'matching.very_good': 'Très bon match',
    'matching.good': 'Bon match',
    'matching.potential': 'Match potentiel',
    'matching.refresh': 'Actualiser',
    'matching.mentors_found': 'mentor(s) trouvé(s) - classés par pertinence',
    'matching.compatibility_score': 'Score de compatibilité',
    'matching.competences': 'Compétences',
    'matching.domain': 'Domaine',
    'matching.reputation': 'Réputation',
    'matching.experience': 'Expérience',

    // Mentors
    'mentors.subtitle': 'Des experts passionnés prêts à vous accompagner',
    'mentors.search_placeholder': 'Rechercher un mentor...',
    'mentors.domaine_placeholder': 'Domaine (ex: Informatique)',
    'mentors.all': 'Tous',
    'mentors.available': 'Disponibles',
    'mentors.reset': 'Réinitialiser',
    'mentors.no_results': 'Aucun mentor trouvé',
    'mentors.expert': 'Expert',
    'mentors.years': 'ans exp.',
    'mentors.sessions': 'sessions',
    'mentors.view_profile': 'Voir le profil',
    'mentors.book_session': 'Réserver une session',
    'mentors.about': 'À propos',
    'mentors.contact': 'Contact',
    'mentors.advanced_filters': 'Filtres avancés',
    'mentors.min_rating': 'Note minimum',
    'mentors.min_experience': 'Expérience minimum',
    'mentors.show_less': 'Voir moins',
    'mentors.show_more_others': 'autres',
    'mentors.found_label': 'mentor(s) trouvé(s)',
    'mentors.unavailable': 'Indisponible',
    'mentors.not_found': 'Mentor non trouvé',
    'mentors.no_bio': 'Aucune description disponible.',
    'mentors.criteria_punctuality': 'Ponctualité',
    'mentors.criteria_pedagogy': 'Pédagogie',
    'mentors.criteria_availability': 'Disponibilité',
    'mentors.reviews': 'Avis',
    'mentors.no_reviews': "Ce mentor n'a pas encore reçu d'avis.",
    'mentors.mentee_only': 'Vous devez être un mentoré pour réserver.',
    'mentors.is_available': 'Disponible',

    // Disponibilités
    'disponibilites.title': 'Mes disponibilités',
    'disponibilites.subtitle': 'Gérez vos créneaux horaires',
    'disponibilites.add': 'Ajouter',
    'disponibilites.cancel': 'Annuler',
    'disponibilites.jour': 'Jour',
    'disponibilites.heure_debut': 'Heure début',
    'disponibilites.heure_fin': 'Heure fin',
    'disponibilites.recurrent': 'Récurrent (chaque semaine)',
    'disponibilites.no_disponibilites': 'Aucune disponibilité',
    'disponibilites.add_disponibilite': 'Ajouter une disponibilité',
    'disponibilites.no_disponibilites_desc': 'Ajoutez vos créneaux horaires',
    'disponibilites.delete_confirm': 'Supprimer cette disponibilité ?',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.back': 'Retour',
    'common.new': 'Nouveau',
    'common.logout': 'Déconnexion',
    'common.login': 'Connexion',
    'common.register': 'Inscription',
    'common.about': 'À propos',
    'common.contact': 'Contact',
    'common.guest': 'Invité',
    'common.role_mentor': 'Mentor',
    'common.role_mentee': 'Mentoré(e)',
    'common.open_menu': 'Ouvrir le menu',
    'common.close_menu': 'Fermer le menu',
    'common.expand_sidebar': 'Agrandir la barre latérale',
    'common.collapse_sidebar': 'Réduire la barre latérale',

    'mentors.top_mentors': 'Nos mentors exceptionnels',
    'mentors.top_mentors_desc': 'Des experts passionnés prêts à vous accompagner',

    'chat.session': 'Session de mentorat',
    'chat.video_call': 'Appel vidéo',
    'chat.no_messages': 'Aucun message. Commencez la conversation !',
    'chat.message_deleted': 'Message supprimé',
    'chat.message_deleted_success': 'Message supprimé avec succès',
    'chat.message_delete_error': 'Impossible de supprimer ce message',
    'chat.delete': 'Supprimer',
    'chat.sending': 'Envoi...',
    'chat.attach_file': 'Joindre des fichiers',
    'chat.emoji': 'Emojis',
    'chat.message_placeholder': 'Écrivez votre message...',
    'chat.send': 'Envoyer',
    'chat.hint': '😊 Emojis | 📎 Fichiers | 🎥 Appel vidéo | ⏎ Envoyer',
    'chat.download': 'Télécharger',
    'chat.call_accepted': 'Appel accepté !',
    'chat.call_rejected': 'Appel refusé',
    'chat.call_ended': 'Appel terminé',
    'chat.connection_error': 'Connexion socket non établie',
    'chat.participant_not_found': "Impossible de trouver l'autre participant",
    'chat.call_in_progress': 'Appel en cours...',
    'chat.enlarge': 'Agrandissement',

    'nav.about': 'À propos',
    'notif.title': 'Notifications',
    'notif.mark_all': 'Tout marquer lu',
    'notif.none': 'Aucune notification',
    'notif.none_desc': "Vous n'avez pas encore de notifications",
    'notif.unread': 'non lue(s)',

    'about.back': "Retour à l'accueil",
    'about.title': 'À propos',
    'about.subtitle': 'Plateforme de Mentorat Académique avec Matching IA',
    'about.project_title': '📖 Notre projet',
    'about.project_p1': "Ce projet de fin d'études vise à concevoir et développer une plateforme numérique de mentorat académique intégrant un algorithme d'intelligence artificielle pour le matching automatique entre mentors et mentorés.",
    'about.project_p2': "La plateforme permet aux étudiants de trouver des mentors adaptés à leurs besoins spécifiques en se basant sur leurs compétences, leurs disponibilités et leurs objectifs d'apprentissage. L'objectif général est de faciliter l'accompagnement académique, d'améliorer la réussite des étudiants et de valoriser l'expertise des mentors au sein de la communauté universitaire.",
    'about.values_title': '🎯 Nos valeurs',
    'about.features_title': '⚡ Fonctionnalités clés',
    'about.val1_title': 'Notre mission',
    'about.val1_desc': "Faciliter l'accès au mentorat académique pour tous les étudiants grâce à l'intelligence artificielle et à une mise en relation intelligente.",
    'about.val2_title': 'Notre communauté',
    'about.val2_desc': "Une communauté de mentors passionnés et d'étudiants motivés, unis pour la réussite de tous et le partage de connaissances.",
    'about.val3_title': 'Notre expertise',
    'about.val3_desc': 'Des algorithmes de matching IA avancés pour des recommandations toujours plus pertinentes et personnalisées.',
    'about.val4_title': 'Nos valeurs',
    'about.val4_desc': 'Excellence, bienveillance, innovation et accessibilité au cœur de notre plateforme de mentorat.',
    'about.feat1_title': 'Matching IA intelligent',
    'about.feat1_desc': 'Notre algorithme analyse les compétences, disponibilités et objectifs pour vous proposer le mentor idéal.',
    'about.feat2_title': 'Suivi de progression',
    'about.feat2_desc': "Visualisez votre évolution grâce à des rapports détaillés et des statistiques personnalisées.",
    'about.feat3_title': 'Accompagnement personnalisé',
    'about.feat3_desc': 'Des sessions de mentorat adaptées à vos besoins avec des experts dans votre domaine.',
    'about.author_role': 'Projet de Fin d\'Études — Université Adventiste Zurcher',
    'about.author_year': 'Mention Informatique — Année académique 2025-2026',

    'session.new_title': 'Nouvelle session',
    'session.new_with': 'avec',
    'session.back': 'Retour au profil',
    'session.date': 'Date',
    'session.time': 'Heure',
    'session.no_slots': 'Aucun créneau disponible pour cette date',
    'session.subject': 'Sujet *',
    'session.subject_placeholder': 'Ex: Aide sur le projet Python',
    'session.desc': 'Description (optionnelle)',
    'session.desc_placeholder': 'Décrivez vos attentes...',
    'session.book': 'Réserver',
    'session.booked': 'Session réservée avec succès !',
    'session.fields_required': 'Veuillez remplir tous les champs',
    'session.loading_error': 'Erreur lors du chargement',
    'notif.see_all': 'Voir toutes les notifications',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.mentors': 'Mentors',
    'nav.sessions': 'Sessions',
    'nav.chat': 'Chat',
    'nav.reports': 'Reports',
    'nav.calendar': 'Calendar',
    'tools.matching': 'AI Matching',
    'tools.profile': 'My profile',
    'tools.disponibilites': 'My availability',

    // Home page
    'home.badge': 'Next generation mentoring platform',
    'home.hero_title': 'Find the mentor who',
    'home.hero_subtitle': 'will reveal you',
    'home.hero_description': 'Join our community and accelerate your learning with personalized mentoring and AI matching',
    'home.start_free': 'Start for free',
    'home.view_mentors': 'View mentors',
    'home.stats_mentors': 'Expert mentors',
    'home.stats_sessions': 'Sessions completed',
    'home.stats_satisfaction': 'Satisfaction rate',
    'home.stats_support': '24/7 Support',
    'home.why_choose_us': 'Why choose our platform?',
    'home.why_choose_us_desc': 'A complete and innovative mentoring experience',
    'home.feature_matching': 'AI Matching',
    'home.feature_matching_desc': 'Find the perfect mentor with our intelligent algorithm',
    'home.feature_booking': 'Easy booking',
    'home.feature_booking_desc': 'Schedule your sessions in few clicks',
    'home.feature_chat': 'Real-time chat',
    'home.feature_chat_desc': 'Instant communication with your mentor',
    'home.feature_video': 'Video conferencing',
    'home.feature_video_desc': 'Online sessions with integrated link',
    'home.feature_certification': 'Certification',
    'home.feature_certification_desc': 'Get progress certificates',
    'home.feature_security': 'Secure',
    'home.feature_security_desc': 'Secure and confidential platform',
    'home.cta_title': 'Ready to start your journey?',
    'home.cta_description': 'Join thousands of students who already found their ideal mentor',
    'home.cta_button': 'Free registration',
    'home.find_mentor': 'Find a mentor',
    'home.explore_by_domain': 'Explore by domain',
    'home.explore_by_domain_desc': 'Find a mentor in your area of interest',
    'home.view_all_domains': 'View all domains',
    'footer.title': 'Academic Mentoring Platform',
    'footer.project': 'Final Year Project',

    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.activity': 'Your activity',
    'dashboard.quick_access': 'Quick access',
    'dashboard.sessions': 'My sessions',
    'dashboard.messages': 'Messages',
    'dashboard.reports': 'Reports',
    'dashboard.find_mentor': 'Find a mentor',
    'dashboard.recommendations': 'AI Recommendations',
    'dashboard.sessions_desc': 'View and manage your sessions',
    'dashboard.messages_desc': 'Chat with your contacts',
    'dashboard.reports_desc': 'Download your reports',
    'dashboard.find_mentor_desc': 'Search for mentors',
    'dashboard.recommendations_desc': 'Suggested mentors for you',
    'dashboard.recent_sessions': 'Recent sessions',
    'dashboard.unread': 'Unread',

    // Profile
    'profile.title': 'My profile',
    'profile.edit': 'Edit',
    'profile.save': 'Save',
    'profile.photo': 'Profile photo',
    'profile.info': 'Personal information',
    'profile.experience': 'Experience',
    'profile.progression': 'Progress',
    'profile.note': 'Average rating',
    'profile.disponibilites': 'My availability',
    'profile.disponibilites_desc': 'Manage your schedule',
    'profile.nom_complet': 'Full name',
    'profile.domaine': 'Field',
    'profile.domaine_placeholder': 'Ex: Computer Science, Marketing, Design...',
    'profile.bio': 'Biography',
    'profile.bio_placeholder': 'Present your background and expertise...',
    'profile.annees_experience': 'Years of experience',
    'profile.disponible': 'Available for mentoring',
    'profile.indisponible': 'Not available',
    'profile.cv': 'CV (PDF)',
    'profile.view_cv': 'View current CV',
    'profile.replace_cv': 'Replace CV',
    'profile.upload_cv': 'Upload CV',
    'profile.niveau_etude': 'Education level',
    'profile.niveau_etude_placeholder': 'Ex: Bachelor, Master, PhD...',
    'profile.objectifs': 'Learning objectives',
    'profile.objectifs_placeholder': 'Describe your learning objectives...',
    'profile.tags': 'Keywords for AI matching',
    'profile.tags_desc': 'These keywords are used by the AI algorithm to find the best mentors.',
    'profile.tags_placeholder': 'Ex: python, machine learning...',
    'profile.tags_hint': 'Press Enter or , to add a tag',
    'common.saving': 'Saving...',

    // ── AUTH ──────────────────────────────────────────────────────────────────
    'auth.login_hero_title': 'Welcome back',
    'auth.login_hero_desc': 'Sign in to find your sessions, mentors and progress.',
    'auth.login_title': 'Login',
    'auth.login_subtitle': 'Access your personal space',
    'auth.login_button': 'Sign in',
    'auth.login_error': 'Incorrect email or password',
    'auth.no_account': "Don't have an account?",
    'auth.register_link': 'Sign up',
    'auth.forgot_password': 'Forgot password?',

    'auth.register_hero_title': 'Join the community',
    'auth.register_hero_desc': 'Create your account and start your mentoring journey today.',
    'auth.register_title': 'Register',
    'auth.register_subtitle': 'Create your free account',
    'auth.register_button': 'Sign up',
    'auth.register_success': 'Registration successful! Welcome 🎉',
    'auth.register_error': 'Error during registration',
    'auth.have_account': 'Already have an account?',
    'auth.login_link': 'Sign in',

    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.lastname': 'Last name',
    'auth.firstname': 'First name',
    'auth.or': 'or',

    'auth.fields_required': 'Please fill in all fields',
    'auth.password_requirements': 'Password does not meet the requirements',
    'auth.password_min_length': 'Minimum 8 characters',
    'auth.password_uppercase': 'One uppercase letter',
    'auth.password_number': 'One number',

    'auth.i_am': 'I am a',
    'auth.role_mentee': 'Mentee',
    'auth.role_mentee_desc': 'I am learning',
    'auth.role_mentor': 'Mentor',
    'auth.role_mentor_desc': 'I am guiding',

    'auth.google_error': 'Error connecting with Google',
    'auth.google_cancelled': 'Google sign-in cancelled',

    'auth.feat1_title': 'Smart AI Matching',
    'auth.feat1_desc': 'Find the perfect mentor with our algorithm.',
    'auth.feat2_title': 'Personalized goals',
    'auth.feat2_desc': 'Track your progress with every session.',
    'auth.feat3_title': 'Secure platform',
    'auth.feat3_desc': 'Your data and conversations are protected.',
    'auth.feat4_title': 'Detailed reports',
    'auth.feat4_desc': 'Download your session reports as PDF.',

    // Sessions
    'sessions.title': 'My sessions',
    'sessions.all': 'All',
    'sessions.pending': 'Pending',
    'sessions.confirmed': 'Confirmed',
    'sessions.in_progress': 'In progress',
    'sessions.completed': 'Completed',
    'sessions.cancelled': 'Cancelled',
    'sessions.confirm': 'Confirm',
    'sessions.cancel': 'Cancel',
    'sessions.start': 'Start',
    'sessions.chat': 'Chat',
    'sessions.with': 'With',
    'sessions.started': 'Session started',
    'sessions.cancel_confirm': 'Cancel this session?',
    'sessions.no_sessions': 'No sessions found',
    'sessions.subtitle': 'Mentoring space',
    'sessions.page_description': 'View, confirm and schedule your mentoring exchanges.',
    'sessions.upcoming': 'Upcoming',
    'sessions.history': 'History',
    'sessions.total': 'Total',
    'sessions.new_session': 'New session',
    'sessions.empty_title': 'No sessions yet',
    'sessions.empty_mentee': 'Book your first mentor to get started.',
    'sessions.empty_mentor': 'Wait for a mentee to contact you.',
    'sessions.explore_mentors': 'Explore mentors',
    'sessions.label_mentee': 'Mentee',
    'sessions.label_mentor': 'Mentor',
    'sessions.reviewed': 'Rated',
    'sessions.visio': 'Video',
    'sessions.rate': 'Rate',
    'sessions.view_report': 'View Report',

    // Chat
    'chat.title': 'Messages',
    'chat.subtitle': 'Chat with your mentors and mentees',
    'chat.no_conversation': 'No conversation',
    'chat.no_conversation_desc': 'You have no active sessions yet.',
    'chat.start': 'Start the conversation!',
    'chat.search_placeholder': 'Search...',
    'chat.no_conversations_desc_alt': 'Book a session to start chatting',
    'chat.yesterday': 'Yesterday',
    'chat.today': 'Today',
    'chat.online': 'Online',
    'chat.typing': 'typing...',

    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Generate and download your reports',
    'reports.no_sessions': 'No completed sessions',
    'reports.no_sessions_desc': 'Reports will be available once your sessions are completed.',
    'reports.generate': 'Generate',
    'reports.download': 'Download',
    'reports.generating': 'Generating report...',
    'reports.downloaded': 'Report downloaded!',
    'reports.search_placeholder': 'Search a report by subject or name...',
    'reports.no_search_results': 'No results',
    'reports.no_search_results_desc': 'No report matches your search.',
    'reports.by_author': 'By {role} {name}',
    'reports.no_summary': 'Download the PDF report to view the full summary of this session.',
    'reports.view_full': 'View in full',
    'reports.session_reports': 'Session reports',
    'reports.session_report': 'Session report',
    'reports.report': 'Report',
    'reports.no_reports': 'No reports generated',
    'reports.no_reports_yet': 'No report',
    'reports.no_reports_desc': 'Generate a report for this session',
    'reports.generate_report': 'Generate report',
    'reports.existing_reports': 'Existing reports',
    'reports.regenerate': 'Regenerate',
    'reports.view_details': 'View details',
    'reports.downloading': 'Downloading report...',
    'reports.generated': 'Report generated successfully!',
    'reports.back_to_reports': 'Back to reports',
    'reports.generate_quick': 'Quick generate',
    'common.back_to_reports': 'Back to reports',

    // Matching
    'matching.title': 'AI Recommendations',
    'matching.subtitle': 'Mentors selected for you',
    'matching.no_results': 'No recommendations',
    'matching.no_results_desc': 'Complete your profile and goals to receive personalized recommendations.',
    'matching.view_profile': 'View profile',
    'matching.book': 'Book',
    'matching.mentor_only': 'AI Matching is reserved for mentees',
    'matching.updated': 'Recommendations updated',
    'matching.excellent': 'Excellent match!',
    'matching.very_good': 'Very good match',
    'matching.good': 'Good match',
    'matching.potential': 'Potential match',
    'matching.refresh': 'Refresh',
    'matching.mentors_found': 'mentor(s) found - ranked by relevance',
    'matching.compatibility_score': 'Compatibility score',
    'matching.competences': 'Skills',
    'matching.domain': 'Domain',
    'matching.reputation': 'Reputation',
    'matching.experience': 'Experience',

    // Mentors
    'mentors.subtitle': 'Passionate experts ready to guide you',
    'mentors.search_placeholder': 'Search for a mentor...',
    'mentors.domaine_placeholder': 'Field (ex: Computer Science)',
    'mentors.all': 'All',
    'mentors.available': 'Available',
    'mentors.reset': 'Reset',
    'mentors.no_results': 'No mentors found',
    'mentors.expert': 'Expert',
    'mentors.years': 'years exp.',
    'mentors.sessions': 'sessions',
    'mentors.view_profile': 'View profile',
    'mentors.book_session': 'Book a session',
    'mentors.about': 'About',
    'mentors.contact': 'Contact',
    'mentors.advanced_filters': 'Advanced filters',
    'mentors.min_rating': 'Minimum rating',
    'mentors.min_experience': 'Minimum experience',
    'mentors.show_less': 'Show less',
    'mentors.show_more_others': 'others',
    'mentors.found_label': 'mentor(s) found',
    'mentors.unavailable': 'Unavailable',
    'mentors.not_found': 'Mentor not found',
    'mentors.no_bio': 'No description available.',
    'mentors.criteria_punctuality': 'Punctuality',
    'mentors.criteria_pedagogy': 'Pedagogy',
    'mentors.criteria_availability': 'Availability',
    'mentors.reviews': 'Reviews',
    'mentors.no_reviews': 'This mentor has not received any reviews yet.',
    'mentors.mentee_only': 'You must be a mentee to book a session.',
    'mentors.is_available': 'Available',

    // Disponibilités
    'disponibilites.title': 'My availability',
    'disponibilites.subtitle': 'Manage your schedule',
    'disponibilites.add': 'Add',
    'disponibilites.cancel': 'Cancel',
    'disponibilites.jour': 'Day',
    'disponibilites.heure_debut': 'Start time',
    'disponibilites.heure_fin': 'End time',
    'disponibilites.recurrent': 'Recurring (every week)',
    'disponibilites.no_disponibilites': 'No availability',
    'disponibilites.add_disponibilite': 'Add availability',
    'disponibilites.no_disponibilites_desc': 'Add your schedule',
    'disponibilites.delete_confirm': 'Delete this availability?',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.new': 'New',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.guest': 'Guest',
    'common.role_mentor': 'Mentor',
    'common.role_mentee': 'Mentee',
    'common.open_menu': 'Open menu',
    'common.close_menu': 'Close menu',
    'common.expand_sidebar': 'Expand sidebar',
    'common.collapse_sidebar': 'Collapse sidebar',

    'mentors.top_mentors': 'Our exceptional mentors',
    'mentors.top_mentors_desc': 'Passionate experts ready to guide you',

    'chat.session': 'Mentoring session',
    'chat.video_call': 'Video call',
    'chat.no_messages': 'No messages. Start the conversation!',
    'chat.message_deleted': 'Message deleted',
    'chat.message_deleted_success': 'Message deleted successfully',
    'chat.message_delete_error': 'Unable to delete this message',
    'chat.delete': 'Delete',
    'chat.sending': 'Sending...',
    'chat.attach_file': 'Attach files',
    'chat.emoji': 'Emojis',
    'chat.message_placeholder': 'Write your message...',
    'chat.send': 'Send',
    'chat.hint': '😊 Emojis | 📎 Files | 🎥 Video call | ⏎ Send',
    'chat.download': 'Download',
    'chat.call_accepted': 'Call accepted!',
    'chat.call_rejected': 'Call rejected',
    'chat.call_ended': 'Call ended',
    'chat.connection_error': 'Socket connection not established',
    'chat.participant_not_found': 'Unable to find the other participant',
    'chat.call_in_progress': 'Calling...',
    'chat.enlarge': 'Enlarged view',

    'nav.about': 'About',
    'notif.title': 'Notifications',
    'notif.mark_all': 'Mark all as read',
    'notif.none': 'No notifications',
    'notif.none_desc': 'You have no notifications yet',
    'notif.unread': 'unread',

    'about.back': 'Back to home',
    'about.title': 'About',
    'about.subtitle': 'Academic Mentoring Platform with AI Matching',
    'about.project_title': '📖 Our project',
    'about.project_p1': 'This final year project aims to design and develop a digital academic mentoring platform integrating an artificial intelligence algorithm for automatic matching between mentors and mentees.',
    'about.project_p2': 'The platform allows students to find mentors suited to their specific needs based on their skills, availability and learning objectives. The overall goal is to facilitate academic support, improve student success and promote mentor expertise within the university community.',
    'about.values_title': '🎯 Our values',
    'about.features_title': '⚡ Key features',
    'about.val1_title': 'Our mission',
    'about.val1_desc': 'Facilitate access to academic mentoring for all students through artificial intelligence and intelligent matchmaking.',
    'about.val2_title': 'Our community',
    'about.val2_desc': 'A community of passionate mentors and motivated students, united for the success of all and the sharing of knowledge.',
    'about.val3_title': 'Our expertise',
    'about.val3_desc': 'Advanced AI matching algorithms for ever more relevant and personalized recommendations.',
    'about.val4_title': 'Our values',
    'about.val4_desc': 'Excellence, kindness, innovation and accessibility at the heart of our mentoring platform.',
    'about.feat1_title': 'Intelligent AI Matching',
    'about.feat1_desc': 'Our algorithm analyzes skills, availability and goals to suggest the ideal mentor for you.',
    'about.feat2_title': 'Progress tracking',
    'about.feat2_desc': 'Visualize your progress with detailed reports and personalized statistics.',
    'about.feat3_title': 'Personalized support',
    'about.feat3_desc': 'Mentoring sessions tailored to your needs with experts in your field.',
    'about.author_role': 'Final Year Project — Zurcher Adventist University',
    'about.author_year': 'Computer Science — Academic Year 2025-2026',

    'session.new_title': 'New session',
    'session.new_with': 'with',
    'session.back': 'Back to profile',
    'session.date': 'Date',
    'session.time': 'Time',
    'session.no_slots': 'No slots available for this date',
    'session.subject': 'Subject *',
    'session.subject_placeholder': 'Ex: Help with Python project',
    'session.desc': 'Description (optional)',
    'session.desc_placeholder': 'Describe your expectations...',
    'session.book': 'Book',
    'session.booked': 'Session booked successfully!',
    'session.fields_required': 'Please fill in all fields',
    'session.loading_error': 'Error loading data',
    'notif.see_all': 'See all notifications',
  },
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language | null;
    if (saved === 'fr' || saved === 'en') {
      setLanguage(saved);
    }
    setMounted(true);
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  if (!mounted) return null;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};